// The list of words the game can pick from, and the list of words you're
// allowed to guess. Add your own! Every word must be exactly 5 letters.

const ANSWERS = [
  "about", "above", "actor", "adopt", "after", "agent", "alarm", "album",
  "alien", "alive", "alone", "along", "amber", "angel", "anger", "angle",
  "apple", "apron", "arena", "argue", "arrow", "aside", "asset", "audio",
  "badge", "baker", "banjo", "basic", "beach", "beard", "began", "begin",
  "being", "belly", "bench", "berry", "birth", "black", "blade", "blame",
  "blank", "blast", "blaze", "bleed", "blend", "bless", "blind", "block",
  "blood", "bloom", "board", "boost", "booth", "brain", "brand", "brave",
  "bread", "break", "brick", "bride", "brief", "bring", "broad", "broke",
  "brown", "brush", "build", "bunch", "burnt", "cabin", "cable", "camel",
  "candy", "canoe", "cargo", "carve", "catch", "cause", "chain", "chair",
  "chalk", "charm", "chart", "chase", "cheap", "check", "cheer", "chess",
  "chest", "chief", "child", "chill", "china", "chose", "civil", "claim",
  "clash", "class", "clean", "clear", "clerk", "click", "cliff", "climb",
  "clock", "close", "cloth", "cloud", "clown", "coach", "coast", "color",
  "comet", "couch", "could", "count", "court", "cover", "crack", "craft",
  "crane", "crash", "crate", "crawl", "crazy", "cream", "crime", "crisp",
  "cross", "crowd", "crown", "crumb", "curve", "cycle", "daily", "dance",
  "dealt", "death", "debut", "delay", "dense", "depth", "diary", "dirty",
  "ditch", "diver", "dodge", "dough", "dozen", "draft", "drain", "drama",
  "drank", "drawn", "dream", "dress", "dried", "drill", "drink", "drive",
  "drove", "dwarf", "eager", "eagle", "early", "earth", "eight", "elbow",
  "elder", "elect", "empty", "enemy", "enjoy", "enter", "entry", "equal",
  "error", "event", "every", "exact", "exist", "extra", "fable", "faith",
  "false", "fancy", "fault", "favor", "feast", "fence", "ferry", "fever",
  "field", "fiber", "fifth", "fight", "final", "first", "flame", "flash",
  "fleet", "flesh", "float", "flock", "flood", "floor", "flour", "fluid",
  "flute", "focus", "force", "forge", "forty", "forum", "found", "frame",
  "fraud", "fresh", "fried", "front", "frost", "fruit", "fully", "funny",
  "ghost", "giant", "given", "glass", "gleam", "globe", "glory", "glove",
  "going", "grace", "grade", "grain", "grand", "grant", "grape", "graph",
  "grasp", "grass", "grave", "great", "green", "greet", "grief", "grill",
  "gross", "group", "grove", "growl", "guard", "guess", "guest", "guide",
  "happy", "harsh", "haunt", "heart", "heavy", "hedge", "hello", "hence",
  "hobby", "honey", "honor", "horse", "hotel", "house", "human", "humor",
  "hurry", "ideal", "image", "imply", "index", "inner", "input", "irony",
  "issue", "ivory", "jeans", "jelly", "jewel", "joint", "judge", "juice",
  "knife", "knock", "known", "label", "labor", "large", "laser", "later",
  "laugh", "layer", "learn", "lease", "least", "leave", "legal", "lemon",
  "level", "light", "limit", "linen", "liver", "lobby", "local", "lodge",
  "logic", "loose", "lower", "loyal", "lucky", "lunar", "lunch", "lyric",
  "magic", "major", "maker", "maple", "march", "match", "maybe", "mayor",
  "meant", "medal", "media", "melon", "mercy", "merit", "metal", "meter",
  "midst", "might", "minor", "mixed", "model", "moist", "money", "month",
  "moral", "motor", "mount", "mouse", "mouth", "movie", "music", "naked",
  "nerve", "never", "newly", "night", "noble", "noise", "north", "novel",
  "nurse", "occur", "ocean", "offer", "often", "olive", "onion", "opera",
  "orbit", "order", "organ", "other", "ought", "outer", "owner", "paint",
  "panel", "panic", "paper", "party", "pasta", "patch", "pause", "peace",
  "peach", "pearl", "pedal", "penny", "perch", "phase", "phone", "photo",
  "piano", "piece", "pilot", "pitch", "pixel", "pizza", "place", "plain",
  "plane", "plant", "plate", "plaza", "point", "polar", "porch", "pound",
  "power", "press", "price", "pride", "prime", "print", "prize", "probe",
  "proof", "proud", "prove", "pulse", "punch", "pupil", "puppy", "purse",
  "queen", "query", "quest", "queue", "quick", "quiet", "quilt", "quite",
  "quote", "radar", "radio", "raise", "rally", "ranch", "range", "rapid",
  "ratio", "reach", "ready", "realm", "rebel", "relax", "relay", "renew",
  "reply", "rhyme", "rider", "ridge", "rifle", "right", "rigid", "rinse",
  "risky", "rival", "river", "roast", "robin", "robot", "rocky", "rough",
  "round", "route", "royal", "rugby", "ruler", "rumor", "rural", "salad",
  "sandy", "sauce", "scale", "scarf", "scene", "scent", "scope", "score",
  "scout", "scrap", "seize", "sense", "serve", "seven", "shade", "shaft",
  "shake", "shall", "shame", "shape", "share", "shark", "sharp", "sheep",
  "sheet", "shelf", "shell", "shift", "shine", "shirt", "shock", "shone",
  "shore", "short", "shout", "shown", "sight", "silly", "since", "siren",
  "sixth", "skate", "skill", "skirt", "slate", "sleep", "slice", "slide",
  "slope", "small", "smart", "smash", "smile", "smoke", "snack", "snake",
  "sneak", "solar", "solid", "solve", "sorry", "sound", "south", "space",
  "spare", "spark", "speak", "speed", "spell", "spend", "spent", "spice",
  "spike", "spine", "spite", "split", "spoke", "spoon", "sport", "spray",
  "squad", "stack", "staff", "stage", "stain", "stair", "stake", "stamp",
  "stand", "stare", "start", "state", "steal", "steam", "steel", "steep",
  "stick", "stiff", "still", "sting", "stock", "stone", "stood", "store",
  "storm", "story", "stove", "strap", "straw", "strip", "study", "stuff",
  "style", "sugar", "suite", "sunny", "super", "surge", "sweat", "sweep",
  "sweet", "swept", "swift", "swing", "sword", "table", "taken", "tally",
  "taste", "teach", "teeth", "tempo", "tenth", "thank", "theft", "theme",
  "there", "thick", "thief", "thing", "think", "third", "those", "three",
  "threw", "throw", "thumb", "tiger", "tight", "timer", "tired", "title",
  "toast", "today", "token", "tooth", "topic", "torch", "total", "touch",
  "tough", "tower", "toxic", "trace", "track", "trade", "trail", "train",
  "trait", "trash", "treat", "trend", "trial", "tribe", "trick", "troop",
  "truck", "truly", "trunk", "trust", "truth", "twice", "twist", "uncle",
  "under", "union", "unite", "unity", "until", "upper", "upset", "urban",
  "usual", "valid", "value", "valve", "vapor", "vault", "venue", "video",
  "vinyl", "viral", "virus", "visit", "vital", "vivid", "vocal", "voice",
  "waist", "waste", "watch", "water", "weary", "weird", "whale", "wheat",
  "wheel", "where", "which", "while", "white", "whole", "whose", "widen",
  "width", "windy", "witch", "woman", "world", "worry", "worse", "worst",
  "worth", "would", "wound", "wrist", "write", "wrong", "wrote", "yacht",
  "yield", "young", "yours", "youth", "zebra",
];

// Any word you're allowed to type as a guess. For now that's just the answer
// list, so if the game rejects a real word, add it here.
const ALLOWED = ANSWERS;
